version: "3.4"

services:

  mariadb:
    build:
      context: ./
      dockerfile: Dockerfile
      target: mariadb
    networks:
      - sp7
    expose: # remove these two lines and uncomment the next two lines if you want to be able to connect to the MariaDB server from outside the container
      - '3306'
    #ports:
    #  - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure

  specify7:
    build:
      context: ./
      dockerfile: Dockerfile
      target: specify7
    ports:
      - '8080:80'   # specify7
      - '8081:8081' # web asset server
    depends_on:
      - mariadb
    networks:
      - sp7
    restart: always
    volumes:
      - ./specify6_thick_client:/usr/local/specify6
      - ./specify7_config:/usr/local/specify_config

  # webportal:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #     target: webportal
  #   ports:
  #     - '80:80'
  #     - '8983:8983' # comment out this line if you want to restrict access to the Solr admin page
  #   tty: true

networks:
  sp7:
    driver: bridge